### Zero and identity

In [1]:
import numpy as np

print('np.zeros([3, 3]):')
print(np.zeros([3, 3]))

np.zeros([3, 3]):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
print('np.identity(3):')
print(np.identity(3))

np.identity(3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Matrix addition

In [4]:
A = np.array([[ 1, 4, 0],
              [-2, 6, 5]])
O = np.zeros([2, 3])

print('A:')
print(A)
print()
print('A + O:')
print(A + O)
print()
print('O + A:')
print(O + A)

A:
[[ 1  4  0]
 [-2  6  5]]

A + O:
[[ 1.  4.  0.]
 [-2.  6.  5.]]

O + A:
[[ 1.  4.  0.]
 [-2.  6.  5.]]


In [5]:
A = np.array([[ 1, 4, 0],
              [-2, 6, 5]])
B = np.array([[-3, 1, -1],
              [3, 0, 2]])

print('A:')
print(A)
print()
print('B:')
print(B)
print()
print('A + B:')
print(A + B)
print()
print('B + A:')
print(B + A)

A:
[[ 1  4  0]
 [-2  6  5]]

B:
[[-3  1 -1]
 [ 3  0  2]]

A + B:
[[-2  5 -1]
 [ 1  6  7]]

B + A:
[[-2  5 -1]
 [ 1  6  7]]


### Scalar multiplication

In [6]:
A = np.array([[ 1, 4, 0],
              [-2, 6, 5]])

print('A:')
print(A)
print()
print('2*A:')
print(2*A)

A:
[[ 1  4  0]
 [-2  6  5]]

2*A:
[[ 2  8  0]
 [-4 12 10]]


# Matrix multiplication

In [7]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
I = np.identity(3)

print('A:')
print(A)
print()
print('A@I:')
print(A@I)
print()
print('I@A:')
print(I@A)

A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

A@I:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

I@A:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [8]:
F = np.array([[6, 3, 10],
              [4, 8,  5]])
S = np.array([[0.10, 0.15],
              [0.40, 0.30],
              [0.10, 0.20]])

print('Fruits numbers F:')
print(F)
print()
print('Store prices S:')
print(S)
print()
print('Total costs FS:')
print(F@S)

Fruits numbers F:
[[ 6  3 10]
 [ 4  8  5]]

Store prices S:
[[0.1  0.15]
 [0.4  0.3 ]
 [0.1  0.2 ]]

Total costs FS:
[[2.8 3.8]
 [4.1 4. ]]


In [9]:
print(F.dot(S))

[[2.8 3.8]
 [4.1 4. ]]


### Matrix inverse

In [12]:
from numpy.linalg import inv
%precision 3

H = np.array([[1/(i + j - 1) 
                for j in range(1, 6)] 
                    for i in range(1, 6)])

print('H =')
print(H)
print()
print('inv(H) =')
print(inv(H))
print()
print('H@inv(H) =')
print(H@inv(H))
print()
print('inv(H)@H =')
print(inv(H)@H)
print()
print('inv(inv(H)) =')
print(inv(inv(H)))

H =
[[1.    0.5   0.333 0.25  0.2  ]
 [0.5   0.333 0.25  0.2   0.167]
 [0.333 0.25  0.2   0.167 0.143]
 [0.25  0.2   0.167 0.143 0.125]
 [0.2   0.167 0.143 0.125 0.111]]

inv(H) =
[[ 2.500e+01 -3.000e+02  1.050e+03 -1.400e+03  6.300e+02]
 [-3.000e+02  4.800e+03 -1.890e+04  2.688e+04 -1.260e+04]
 [ 1.050e+03 -1.890e+04  7.938e+04 -1.176e+05  5.670e+04]
 [-1.400e+03  2.688e+04 -1.176e+05  1.792e+05 -8.820e+04]
 [ 6.300e+02 -1.260e+04  5.670e+04 -8.820e+04  4.410e+04]]

H@inv(H) =
[[ 1.000e+00  2.239e-13 -1.553e-12 -2.434e-12  2.672e-12]
 [-2.951e-14  1.000e+00 -1.737e-12  1.422e-12 -4.080e-13]
 [-1.312e-14  2.298e-13  1.000e+00 -1.379e-12  9.496e-13]
 [-1.421e-14  4.547e-13  9.095e-13  1.000e+00  0.000e+00]
 [-5.465e-15  2.040e-13  6.608e-13 -8.708e-13  1.000e+00]]

inv(H)@H =
[[ 1.000e+00 -4.378e-12 -3.535e-12 -2.984e-12 -2.568e-12]
 [ 1.678e-11  1.000e+00  9.909e-12  8.868e-12  7.404e-12]
 [-3.736e-12 -4.769e-12  1.000e+00 -2.728e-12 -2.573e-12]
 [-3.890e-12 -3.428e-12 -4.498e-12  1.00