In [8]:
import numpy as np

In [9]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [10]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [11]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [12]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [13]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [14]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.dot(x, np.ones(3))

array([ 6., 15.])

In [17]:
x @ np.ones(3)

array([ 6., 15.])

In [18]:
from numpy.linalg import inv, qr

%precision 3
X = np.random.randn(5, 5)
X

array([[ 0.241, -0.861, -0.325,  0.478, -0.016],
       [ 1.   ,  0.74 , -1.123,  1.415, -0.936],
       [-0.658,  0.722, -0.225, -0.018, -0.774],
       [-0.705, -0.34 ,  1.796, -0.626, -0.347],
       [ 0.72 , -0.361, -0.415, -0.153,  0.411]])

In [19]:
X.T  # transpose of matrix X

array([[ 0.241,  1.   , -0.658, -0.705,  0.72 ],
       [-0.861,  0.74 ,  0.722, -0.34 , -0.361],
       [-0.325, -1.123, -0.225,  1.796, -0.415],
       [ 0.478,  1.415, -0.018, -0.626, -0.153],
       [-0.016, -0.936, -0.774, -0.347,  0.411]])

In [20]:
mat = X.T.dot(X)
mat

array([[ 2.506,  0.037, -2.618,  1.872,  0.111],
       [ 0.037,  2.055, -1.174,  0.891, -1.267],
       [-2.618, -1.174,  4.817, -2.801,  0.436],
       [ 1.872,  0.891, -2.801,  2.646, -1.164],
       [ 0.111, -1.267,  0.436, -1.164,  1.765]])

In [21]:
mat2 = X.T@X
mat2

array([[ 2.506,  0.037, -2.618,  1.872,  0.111],
       [ 0.037,  2.055, -1.174,  0.891, -1.267],
       [-2.618, -1.174,  4.817, -2.801,  0.436],
       [ 1.872,  0.891, -2.801,  2.646, -1.164],
       [ 0.111, -1.267,  0.436, -1.164,  1.765]])

In [22]:
inv(mat)

array([[ 2.074e+00, -1.041e-01,  3.924e-03, -2.140e+00, -1.617e+00],
       [-1.041e-01,  1.470e+00,  8.567e-01,  1.211e+00,  1.649e+00],
       [ 3.924e-03,  8.567e-01,  1.245e+00,  1.637e+00,  1.387e+00],
       [-2.140e+00,  1.211e+00,  1.637e+00,  4.903e+00,  3.833e+00],
       [-1.617e+00,  1.649e+00,  1.387e+00,  3.833e+00,  4.037e+00]])

In [23]:
mat.dot(inv(mat))

array([[ 1.000e+00, -2.972e-16, -1.609e-16, -1.748e-15, -9.550e-16],
       [-1.396e-16,  1.000e+00,  2.471e-16,  6.594e-16,  1.575e-15],
       [-2.302e-16,  1.286e-16,  1.000e+00, -3.654e-17, -7.659e-16],
       [ 5.529e-16,  2.509e-16, -1.796e-16,  1.000e+00,  6.548e-16],
       [-1.631e-16, -1.082e-16,  1.864e-16, -1.165e-16,  1.000e+00]])

In [24]:
Q, R = qr(X)  # decompose matrix X into factors orthogonal Q and upper-triangular R

In [25]:
R

array([[-1.583, -0.023,  1.654, -1.183, -0.07 ],
       [ 0.   , -1.433,  0.793, -0.603,  0.885],
       [ 0.   ,  0.   ,  1.206, -0.305, -0.124],
       [ 0.   ,  0.   ,  0.   , -0.889,  0.844],
       [ 0.   ,  0.   ,  0.   ,  0.   , -0.498]])

In [26]:
Q

array([[-0.152,  0.603, -0.457, -0.586,  0.247],
       [-0.632, -0.506,  0.267, -0.5  ,  0.154],
       [ 0.416, -0.51 , -0.422, -0.043,  0.622],
       [ 0.445,  0.23 ,  0.728, -0.293,  0.364],
       [-0.455,  0.259,  0.109,  0.564,  0.629]])

In [27]:
Q.T

array([[-0.152, -0.632,  0.416,  0.445, -0.455],
       [ 0.603, -0.506, -0.51 ,  0.23 ,  0.259],
       [-0.457,  0.267, -0.422,  0.728,  0.109],
       [-0.586, -0.5  , -0.043, -0.293,  0.564],
       [ 0.247,  0.154,  0.622,  0.364,  0.629]])

In [28]:
Q@Q.T  # should be the identity matrix I

array([[ 1.000e+00,  7.185e-17, -3.634e-17, -6.458e-17,  5.426e-17],
       [ 7.185e-17,  1.000e+00, -4.115e-17,  3.570e-17,  9.169e-17],
       [-3.634e-17, -4.115e-17,  1.000e+00,  3.364e-17, -4.806e-17],
       [-6.458e-17,  3.570e-17,  3.364e-17,  1.000e+00, -1.005e-18],
       [ 5.426e-17,  9.169e-17, -4.806e-17, -1.005e-18,  1.000e+00]])

In [29]:
inv(Q)  # should equal Q.T

array([[-0.152, -0.632,  0.416,  0.445, -0.455],
       [ 0.603, -0.506, -0.51 ,  0.23 ,  0.259],
       [-0.457,  0.267, -0.422,  0.728,  0.109],
       [-0.586, -0.5  , -0.043, -0.293,  0.564],
       [ 0.247,  0.154,  0.622,  0.364,  0.629]])

In [30]:
Q@R  # Q@R should equal X

array([[ 0.241, -0.861, -0.325,  0.478, -0.016],
       [ 1.   ,  0.74 , -1.123,  1.415, -0.936],
       [-0.658,  0.722, -0.225, -0.018, -0.774],
       [-0.705, -0.34 ,  1.796, -0.626, -0.347],
       [ 0.72 , -0.361, -0.415, -0.153,  0.411]])