In [5]:
import numpy as np

A = np.array([[1, -1, -1],
              [3, -3, 2],
              [2, -1, 1]])

Ainv = np.linalg.inv(A)
Ainv

array([[ 2.00000000e-01, -4.00000000e-01,  1.00000000e+00],
       [-2.00000000e-01, -6.00000000e-01,  1.00000000e+00],
       [-6.00000000e-01,  2.00000000e-01, -3.33066907e-17]])

In [6]:
b = [2, 16, 9]

In [7]:
A@Ainv

array([[ 1.00000000e+00, -8.32667268e-17,  3.33066907e-17],
       [ 0.00000000e+00,  1.00000000e+00, -6.66133815e-17],
       [ 0.00000000e+00, -1.38777878e-16,  1.00000000e+00]])

In [8]:
np.linalg.inv(A)@b

array([ 3., -1.,  2.])

In [9]:
%timeit np.linalg.inv(A)@b
%timeit np.linalg.solve(A, b)

13.6 µs ± 3.87 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
13.3 µs ± 767 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
