In [1]:
import numpy as np

A = np.array([[1, -1, -1],
              [3, -3, 2],
              [2, -1, 1]])
b = [2, 16, 9]

np.linalg.solve(A, b)

array([ 3., -1.,  2.])

In [2]:
import numpy as np

A = np.array([[1, -1, -1],
              [3, -3, 2],
              [2, -1, 1]])

In [3]:
x1 = np.linalg.solve(A, [1, 0, 0])
x1

array([ 0.2, -0.2, -0.6])

In [4]:
x2 = np.linalg.solve(A, [0, 1, 0])
x2

array([-0.4, -0.6,  0.2])

In [5]:
x3 = np.linalg.solve(A, [0, 0, 1])
x3

array([ 1.00000000e+00,  1.00000000e+00, -3.33066907e-17])

In [6]:
Ainv = np.array([x1, x2, x3]).T
Ainv

array([[ 2.00000000e-01, -4.00000000e-01,  1.00000000e+00],
       [-2.00000000e-01, -6.00000000e-01,  1.00000000e+00],
       [-6.00000000e-01,  2.00000000e-01, -3.33066907e-17]])

In [7]:
import numpy as np

A = np.array([[1, -1, -1],
              [3, -3, 2],
              [2, -1, 1]])

Ainv = np.linalg.inv(A)
Ainv

array([[ 2.00000000e-01, -4.00000000e-01,  1.00000000e+00],
       [-2.00000000e-01, -6.00000000e-01,  1.00000000e+00],
       [-6.00000000e-01,  2.00000000e-01, -3.33066907e-17]])

In [8]:
A@Ainv

array([[ 1.00000000e+00, -8.32667268e-17,  3.33066907e-17],
       [ 0.00000000e+00,  1.00000000e+00, -6.66133815e-17],
       [ 0.00000000e+00, -1.38777878e-16,  1.00000000e+00]])

In [9]:
np.linalg.inv(A)@b

array([ 3., -1.,  2.])

In [10]:
%timeit np.linalg.inv(A)@b
%timeit np.linalg.solve(A, b)

13 µs ± 372 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
11.7 µs ± 873 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [11]:
# Singular matrix!
A = np.array([[4, 2],
              [8, 4]])

Ainv = np.linalg.inv(A)
Ainv

LinAlgError: Singular matrix

In [12]:
np.linalg.solve(A, [1, 0])

LinAlgError: Singular matrix

In [13]:
np.linalg.solve(A, [0, 1])

LinAlgError: Singular matrix