In [4]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
from sklearn import preprocessing
from scipy.linalg import svd as SVD
from  mpl_toolkits.mplot3d import Axes3D

A = np.array([
    [1, 1, 1, 0, 0],
    [3, 3, 3, 0, 0],
    [4, 4, 4, 0, 0],
    [5, 5, 5, 0, 0],
    [0, 2, 0, 4, 4],
    [0, 0, 0, 5, 5],
    [0, 1, 0, 2, 2]
])
print(A)

[[1 1 1 0 0]
 [3 3 3 0 0]
 [4 4 4 0 0]
 [5 5 5 0 0]
 [0 2 0 4 4]
 [0 0 0 5 5]
 [0 1 0 2 2]]


In [5]:
U, S, V = SVD(A)
U.shape, S.shape, V.shape

((7, 7), (5,), (5, 5))

In [7]:
print(S)

[1.24810147e+01 9.50861406e+00 1.34555971e+00 1.84716760e-16
 9.74452038e-33]


In [13]:
sigma = np.zeros((7, 5))
for i in range(5):
    sigma[i, i] = S[i]
    
print(sigma)

[[1.24810147e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 9.50861406e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.34555971e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.84716760e-16
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  9.74452038e-33]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]]


In [14]:
S[0]

12.481014693580397

In [15]:
S[1]

9.508614056636775

In [16]:
AR = U@sigma@V
print(np.round(AR))

[[ 1.  1.  1.  0.  0.]
 [ 3.  3.  3. -0. -0.]
 [ 4.  4.  4.  0. -0.]
 [ 5.  5.  5. -0. -0.]
 [ 0.  2. -0.  4.  4.]
 [ 0.  0. -0.  5.  5.]
 [ 0.  1. -0.  2.  2.]]
