In [7]:
import math
import numpy as np
from numpy.linalg import norm, eig

%precision 3
np.set_printoptions(precision=3, suppress=True)

In [8]:
def verify(values, vectors):
    for i in range(len(values)):
        value = values[i]
        vector = vectors[:, i]
        
        print()
        print(f'norm({vector}) = {norm(vector):.3f}')
        print(f'Av = {A@vector}')
        print(f'𝜆v = {value*vector}')

In [9]:
def test_eig(A):
    values, vectors = eig(A)
    
    print('Eigenvalues:')
    print(values)
    print()
    print('Eigenvectors:')
    print(vectors)    
    
    verify(values, vectors)

In [10]:
A = np.array([[1, 2,  3],
              [3, 2,  1],
              [1, 0, -1]])


In [11]:
test_eig(A)

Eigenvalues:
[ 4.317 -2.317  0.   ]

Eigenvectors:
[[ 0.584  0.736  0.408]
 [ 0.804 -0.382 -0.816]
 [ 0.11  -0.559  0.408]]

norm([0.584 0.804 0.11 ]) = 1.000
Av = [2.522 3.471 0.474]
𝜆v = [2.522 3.471 0.474]

norm([ 0.736 -0.382 -0.559]) = 1.000
Av = [-1.705  0.885  1.295]
𝜆v = [-1.705  0.885  1.295]

norm([ 0.408 -0.816  0.408]) = 1.000
Av = [-0. -0. -0.]
𝜆v = [ 0. -0.  0.]


In [12]:
A = np.array([[1, 0, 0,   0],
              [0, 1, 5, -10],
              [1, 0, 2,   0],
              [1, 0, 0,  3]])


In [13]:
test_eig(A)

Eigenvalues:
[1. 3. 2. 1.]

Eigenvectors:
[[ 0.     0.     0.     0.667]
 [ 1.    -0.981  0.981  0.   ]
 [ 0.     0.     0.196 -0.667]
 [ 0.     0.196  0.    -0.333]]

norm([0. 1. 0. 0.]) = 1.000
Av = [0. 1. 0. 0.]
𝜆v = [0. 1. 0. 0.]

norm([ 0.    -0.981  0.     0.196]) = 1.000
Av = [ 0.    -2.942  0.     0.588]
𝜆v = [ 0.    -2.942  0.     0.588]

norm([0.    0.981 0.196 0.   ]) = 1.000
Av = [0.    1.961 0.392 0.   ]
𝜆v = [0.    1.961 0.392 0.   ]

norm([ 0.667  0.    -0.667 -0.333]) = 1.000
Av = [ 0.667  0.    -0.667 -0.333]
𝜆v = [ 0.667  0.    -0.667 -0.333]


In [14]:
# must have x[1] = 1
# need high tolerance = 1.0e-12

A = np.array([[1, -3, 3],
              [3, -5, 3],
              [6, -6, 4]])


In [15]:
test_eig(A)

Eigenvalues:
[ 4. -2. -2.]

Eigenvectors:
[[ 0.408 -0.408 -0.305]
 [ 0.408  0.408 -0.808]
 [ 0.816  0.816 -0.503]]

norm([0.408 0.408 0.816]) = 1.000
Av = [1.633 1.633 3.266]
𝜆v = [1.633 1.633 3.266]

norm([-0.408  0.408  0.816]) = 1.000
Av = [ 0.816 -0.816 -1.633]
𝜆v = [ 0.816 -0.816 -1.633]

norm([-0.305 -0.808 -0.503]) = 1.000
Av = [0.61  1.617 1.007]
𝜆v = [0.61  1.617 1.007]


In [16]:
# wrong eigenvectors unless x[1] = 1

A = np.array([[ 92, -32, -15],
              [-64,  34,  39],
              [176, -68, -99]])


In [17]:
test_eig(A)

Eigenvalues:
[ 88.519 -70.791   9.272]

Eigenvectors:
[[ 0.655  0.02   0.361]
 [-0.261 -0.338  0.933]
 [ 0.709  0.941  0.001]]

norm([ 0.655 -0.261  0.709]) = 1.000
Av = [ 57.958 -23.125  62.783]
𝜆v = [ 57.958 -23.125  62.783]

norm([ 0.02  -0.338  0.941]) = 1.000
Av = [ -1.437  23.914 -66.614]
𝜆v = [ -1.437  23.914 -66.614]

norm([0.361 0.933 0.001]) = 1.000
Av = [3.347 8.647 0.009]
𝜆v = [3.347 8.647 0.009]


In [18]:
# sigular unless x[1] = 1

A = np.array([[1, -2, 1],
              [0,  0, 0],
              [0,  1, 1]])


In [19]:
test_eig(A)

Eigenvalues:
[1. 1. 0.]

Eigenvectors:
[[ 1.    -1.     0.905]
 [ 0.     0.     0.302]
 [ 0.     0.    -0.302]]

norm([1. 0. 0.]) = 1.000
Av = [1. 0. 0.]
𝜆v = [1. 0. 0.]

norm([-1.  0.  0.]) = 1.000
Av = [-1.  0.  0.]
𝜆v = [-1.  0.  0.]

norm([ 0.905  0.302 -0.302]) = 1.000
Av = [0. 0. 0.]
𝜆v = [ 0.  0. -0.]


In [20]:
# singular unless x[1] = 1

A = np.array([[6, 3, -9],
              [0, 9, 15],
              [0, 0, 15]])


In [21]:
test_eig(A)

Eigenvalues:
[ 6.  9. 15.]

Eigenvectors:
[[ 1.     0.707 -0.062]
 [ 0.     0.707  0.927]
 [ 0.     0.     0.371]]

norm([1. 0. 0.]) = 1.000
Av = [6. 0. 0.]
𝜆v = [6. 0. 0.]

norm([0.707 0.707 0.   ]) = 1.000
Av = [6.364 6.364 0.   ]
𝜆v = [6.364 6.364 0.   ]

norm([-0.062  0.927  0.371]) = 1.000
Av = [-0.927 13.901  5.56 ]
𝜆v = [-0.927 13.901  5.56 ]


In [22]:
# singular always

A = np.array([[2,  0],
              [0, -1]])


In [23]:
test_eig(A)

Eigenvalues:
[ 2. -1.]

Eigenvectors:
[[1. 0.]
 [0. 1.]]

norm([1. 0.]) = 1.000
Av = [2. 0.]
𝜆v = [2. 0.]

norm([0. 1.]) = 1.000
Av = [ 0. -1.]
𝜆v = [-0. -1.]


In [24]:
# singular always

A = np.array([[1, 0, 0], 
              [1, 1, 0], 
              [0, 0, 1]])

In [25]:
test_eig(A)

Eigenvalues:
[1. 1. 1.]

Eigenvectors:
[[ 0.  0.  0.]
 [ 1. -1.  0.]
 [ 0.  0.  1.]]

norm([0. 1. 0.]) = 1.000
Av = [0. 1. 0.]
𝜆v = [0. 1. 0.]

norm([ 0. -1.  0.]) = 1.000
Av = [ 0. -1.  0.]
𝜆v = [ 0. -1.  0.]

norm([0. 0. 1.]) = 1.000
Av = [0. 0. 1.]
𝜆v = [0. 0. 1.]
